#!/usr/bin/env bash
# AUTO-GENERATED by OrqaStudio — do not edit manually
# Session start hook — runs on first UserPromptSubmit of a new session

# Only run once per session
GUARD="tmp/.session-started"
if [ -f "$GUARD" ]; then
    exit 0
fi
mkdir -p tmp
touch "$GUARD"

# Check for stashes
STASHES=$(git stash list 2>/dev/null)
if [ -n "$STASHES" ]; then
    echo "WARNING: Git stashes found! Investigate and commit before proceeding:"
    echo "$STASHES"
    echo ""
fi

# Check for stale worktrees (git-linked)
# Use git rev-parse instead of pwd — pwd returns POSIX paths on MINGW64
# while git worktree list returns Windows-style paths, causing false matches
WORKTREES=$(git worktree list 2>/dev/null | grep -v "$(git rev-parse --show-toplevel 2>/dev/null)")
if [ -n "$WORKTREES" ]; then
    echo "WARNING: Non-main worktrees detected! Check if these need cleanup:"
    echo "$WORKTREES"
    echo ""
fi

# Check for orphaned worktree directories
# Use git rev-parse for consistent path format across platforms
PARENT_DIR=$(dirname "$(git rev-parse --show-toplevel 2>/dev/null)")
ORPHANS=$(ls -d "$PARENT_DIR"/orqa-* 2>/dev/null)
if [ -n "$ORPHANS" ]; then
    echo "WARNING: Orphaned worktree directories found (no .git link, likely from prior sessions):"
    echo "$ORPHANS"
    echo ""
    echo "Check for stale processes: ps -ef | grep orqa-"
    echo "Then: kill <pids> && rm -rf <directory>"
    echo ""
fi

# Check for session state from previous session
if [ -f "tmp/session-state.md" ]; then
    echo "PREVIOUS SESSION STATE FOUND (tmp/session-state.md):"
    cat "tmp/session-state.md"
    echo ""
    echo "Review the above and continue where the previous session left off."
    echo ""
fi

# Delegation reminder
echo "ORCHESTRATOR REMINDERS:"
echo "- You coordinate. You do NOT implement. Delegate to specialized agents."
echo "- Available agents: backend-engineer, frontend-engineer, designer, debugger,"
echo "  test-engineer, code-reviewer, data-engineer, devops-engineer,"
echo "  documentation-writer, security-engineer, refactor-agent, agent-maintainer,"
echo "  systems-architect, qa-tester, ux-reviewer"
echo ""

# Dogfood detection
if [ -f ".orqa/project.json" ]; then
    DOGFOOD=$(grep -o '"dogfood"[[:space:]]*:[[:space:]]*true' .orqa/project.json 2>/dev/null)
    if [ -n "$DOGFOOD" ]; then
        echo "DOGFOOD MODE ACTIVE: You are editing the app you are running inside."
        echo "- Use 'make dev' (--no-watch) — never 'make dev-watch'"
        echo "- After Rust changes: write session state, then ask user to restart"
        echo "- See .orqa/rules/dogfood-mode.md for full rules"
        echo ""
    fi
fi

echo "SESSION START CHECKLIST:"
echo "- Read TODO.md for current tasks"
echo "- Check BLOCKERS.md for known issues"
echo "- Embeddings server needed for ChunkHound: ensure localhost:11435 is running"
echo ""
