#!/usr/bin/env bash
# AUTO-GENERATED by OrqaStudio — do not edit manually
# Session start hook — runs on first UserPromptSubmit of a new session

# Only run once per session
GUARD="tmp/.session-started"
if [ -f "$GUARD" ]; then
    exit 0
fi
mkdir -p tmp
touch "$GUARD"

# Check for stashes
STASHES=$(git stash list 2>/dev/null)
if [ -n "$STASHES" ]; then
    echo "WARNING: Git stashes found! Investigate and commit before proceeding:"
    echo "$STASHES"
    echo ""
fi

# Check for stale worktrees (git-linked)
# Use git rev-parse instead of pwd — pwd returns POSIX paths on MINGW64
# while git worktree list returns Windows-style paths, causing false matches
WORKTREES=$(git worktree list 2>/dev/null | grep -v "$(git rev-parse --show-toplevel 2>/dev/null)")
if [ -n "$WORKTREES" ]; then
    echo "WARNING: Non-main worktrees detected! Check if these need cleanup:"
    echo "$WORKTREES"
    echo ""
fi

# Check for orphaned worktree directories
# Use git rev-parse for consistent path format across platforms
PARENT_DIR=$(dirname "$(git rev-parse --show-toplevel 2>/dev/null)")
ORPHANS=$(ls -d "$PARENT_DIR"/orqa-* 2>/dev/null)
if [ -n "$ORPHANS" ]; then
    echo "WARNING: Orphaned worktree directories found (no .git link, likely from prior sessions):"
    echo "$ORPHANS"
    echo ""
    echo "Check for stale processes: ps -ef | grep orqa-"
    echo "Then: kill <pids> && rm -rf <directory>"
    echo ""
fi

# Check for uncommitted changes on main
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null)
if [ "$CURRENT_BRANCH" = "main" ]; then
    UNCOMMITTED=$(git status --short 2>/dev/null | wc -l | tr -d ' ')
    if [ "$UNCOMMITTED" -gt 20 ]; then
        echo "WARNING: $UNCOMMITTED uncommitted files on main! Commit before starting new work."
        echo "Run: git status --short"
        echo ""
    elif [ "$UNCOMMITTED" -gt 0 ]; then
        echo "NOTE: $UNCOMMITTED uncommitted files on main. Consider committing before starting new work."
        echo ""
    fi
fi

# Check for session state from previous session
if [ -f "tmp/session-state.md" ]; then
    echo "PREVIOUS SESSION STATE FOUND (tmp/session-state.md):"
    cat "tmp/session-state.md"
    echo ""
    echo "Review the above and continue where the previous session left off."
    echo ""
fi

# Delegation reminder
echo "ORCHESTRATOR REMINDERS:"
echo "- You coordinate. You do NOT implement. Delegate to specialized agents."
echo "- Universal roles (AD-029): researcher, planner, implementer, reviewer, writer, designer"
echo "- Roles are specialised via skills at runtime (e.g., implementer + rust-async-patterns = backend specialist)"
echo ""

# Dogfood detection
if [ -f ".orqa/project.json" ]; then
    DOGFOOD=$(grep -o '"dogfood"[[:space:]]*:[[:space:]]*true' .orqa/project.json 2>/dev/null)
    if [ -n "$DOGFOOD" ]; then
        echo "DOGFOOD MODE ACTIVE: You are editing the app you are running inside."
        echo "- Use 'make dev' (--no-watch) — never 'make dev-watch'"
        echo "- After Rust changes: write session state, then ask user to restart"
        echo "- See .orqa/governance/rules/RULE-009.md for full rules"
        echo ""
    fi
fi

echo "SESSION START CHECKLIST:"
echo "- Check .orqa/planning/tasks/ for current tasks"
echo "- Check .orqa/planning/epics/ for active epics"
echo "- Embeddings server needed for ChunkHound: ensure localhost:11435 is running"
echo ""
