//! Hook Manager — generates dispatcher scripts for plugin-declared hooks.
//!
//! Reads `HookRegistration` entries from `plugin-hooks.json` (written by the
//! frontend when plugins with `provides.hooks` are loaded), and generates
//! thin shell dispatcher scripts in the project's `.githooks/` directory.
//!
//! The dispatcher approach means:
//! - Adding/removing a plugin with hooks automatically updates the dispatchers
//! - The generated scripts delegate to the plugin's entrypoints
//! - The existing `.githooks/pre-commit` is preserved as a "legacy" hook
//!   that runs alongside plugin hooks

use serde::{Deserialize, Serialize};
use std::path::Path;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A hook registration loaded from plugin-hooks.json.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisteredHook {
    /// Plugin that provides this hook.
    pub plugin: String,
    /// Unique hook key within the plugin.
    pub key: String,
    /// Git/app event that triggers this hook.
    pub event: String,
    /// Runtime: "node" or "system".
    pub runtime: String,
    /// Entrypoint path (resolved relative to project root).
    pub entrypoint: String,
    /// Additional CLI arguments.
    #[serde(default)]
    pub args: Vec<String>,
}

/// Summary of a hook generation operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookGenerationResult {
    /// Number of dispatcher scripts generated.
    pub dispatchers_written: usize,
    /// Events that have dispatchers.
    pub events: Vec<String>,
    /// Hooks that were included.
    pub hooks: Vec<String>,
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/// Config file written by the frontend/SDK when hook plugins are registered.
const HOOKS_CONFIG_FILENAME: &str = "plugin-hooks.json";

/// Marker comment in generated dispatcher scripts.
const GENERATED_MARKER: &str =
    "# AUTO-GENERATED by OrqaStudio plugin system — do not edit manually";

/// Read the hook registry from the config file at the project root.
pub fn read_hook_registry(project_root: &Path) -> Vec<RegisteredHook> {
    let config_path = project_root.join(HOOKS_CONFIG_FILENAME);
    if !config_path.exists() {
        return vec![];
    }

    match std::fs::read_to_string(&config_path) {
        Ok(contents) => serde_json::from_str(&contents).unwrap_or_default(),
        Err(_) => vec![],
    }
}

// ---------------------------------------------------------------------------
// Git event → hook script name mapping
// ---------------------------------------------------------------------------

/// Map plugin hook events to git hook filenames.
/// App-level events (artifact-change, session-start) don't map to git hooks.
fn git_hook_filename(event: &str) -> Option<&'static str> {
    match event {
        "pre-commit" => Some("pre-commit"),
        "post-commit" => Some("post-commit"),
        "pre-push" => Some("pre-push"),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Dispatcher Generation
// ---------------------------------------------------------------------------

/// Generate a shell command line for a registered hook.
fn hook_command_line(hook: &RegisteredHook) -> String {
    let mut parts = Vec::new();

    match hook.runtime.as_str() {
        "node" => {
            parts.push("node".to_string());
            parts.push(format!("\"{}\"", hook.entrypoint));
        }
        _ => {
            parts.push(format!("\"{}\"", hook.entrypoint));
        }
    }

    for arg in &hook.args {
        parts.push(format!("\"{arg}\""));
    }

    parts.join(" ")
}

/// Generate dispatcher script content for a given git event.
///
/// The dispatcher runs all registered hooks for that event sequentially.
/// If any hook exits non-zero, the dispatcher exits non-zero (blocking the
/// git operation for pre-* hooks).
fn generate_dispatcher(event: &str, hooks: &[&RegisteredHook]) -> String {
    use std::fmt::Write as _;

    let mut script = String::new();

    script.push_str("#!/usr/bin/env bash\n");
    script.push_str(GENERATED_MARKER);
    script.push('\n');
    let _ = writeln!(
        script,
        "# Dispatcher for '{event}' — runs all plugin-registered hooks for this event."
    );
    script.push_str("# Regenerate with: OrqaStudio Settings > Plugins > Regenerate Hooks\n\n");
    script.push_str("set -euo pipefail\n\n");

    // Run legacy hook if it exists (preserved from before plugin management)
    let legacy_name = format!("{event}.legacy");
    let _ = write!(
        script,
        "# Run legacy hook if preserved\n\
         if [ -f \"$(dirname \"$0\")/{legacy_name}\" ]; then\n\
         \techo \"--- [{event}] legacy hook ---\"\n\
         \tbash \"$(dirname \"$0\")/{legacy_name}\" \"$@\"\n\
         fi\n\n"
    );

    for hook in hooks {
        let cmd = hook_command_line(hook);
        let plugin = &hook.plugin;
        let key = &hook.key;
        let _ = write!(
            script,
            "# Plugin: {plugin} — hook: {key}\n\
             echo \"--- [{event}] {plugin}: {key} ---\"\n\
             {cmd} \"$@\"\n\n",
        );
    }

    let _ = writeln!(script, "echo \"=== [{event}] All plugin hooks passed ===\"");

    script
}

/// Generate (or update) dispatcher scripts in the `.githooks/` directory.
///
/// Groups registered hooks by event, generates a dispatcher script for each
/// git-mapped event, and writes them to `{project_root}/.githooks/`.
///
/// If a non-generated hook already exists for an event, it is renamed to
/// `{event}.legacy` before the dispatcher is written.
pub fn generate_dispatchers(project_root: &Path) -> Result<HookGenerationResult, String> {
    let hooks = read_hook_registry(project_root);

    // Group hooks by event
    let mut by_event: std::collections::HashMap<String, Vec<&RegisteredHook>> =
        std::collections::HashMap::new();
    for hook in &hooks {
        by_event.entry(hook.event.clone()).or_default().push(hook);
    }

    let hooks_dir = project_root.join(".githooks");
    std::fs::create_dir_all(&hooks_dir).map_err(|e| format!("failed to create .githooks/: {e}"))?;

    let mut dispatchers_written = 0;
    let mut events = Vec::new();
    let mut hook_keys = Vec::new();

    for (event, event_hooks) in &by_event {
        let Some(filename) = git_hook_filename(event) else {
            continue; // App-level events don't generate git hooks
        };

        let hook_path = hooks_dir.join(filename);
        let legacy_path = hooks_dir.join(format!("{filename}.legacy"));

        // Preserve existing non-generated hook as legacy
        if hook_path.exists() && !legacy_path.exists() {
            let existing = std::fs::read_to_string(&hook_path).unwrap_or_default();
            if !existing.contains(GENERATED_MARKER) {
                std::fs::rename(&hook_path, &legacy_path)
                    .map_err(|e| format!("failed to preserve legacy hook: {e}"))?;
            }
        }

        let script = generate_dispatcher(event, event_hooks);
        std::fs::write(&hook_path, &script)
            .map_err(|e| format!("failed to write {filename}: {e}"))?;

        // Make executable on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o755);
            std::fs::set_permissions(&hook_path, perms)
                .map_err(|e| format!("failed to set permissions on {filename}: {e}"))?;
        }

        dispatchers_written += 1;
        events.push(event.clone());
        for hook in event_hooks {
            hook_keys.push(format!("{}:{}", hook.plugin, hook.key));
        }
    }

    Ok(HookGenerationResult {
        dispatchers_written,
        events,
        hooks: hook_keys,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registered_hook_deserialization() {
        let json = r#"[{
            "plugin": "@orqastudio/plugin-integrity",
            "key": "pre-commit-integrity",
            "event": "pre-commit",
            "runtime": "node",
            "entrypoint": "node_modules/.bin/orqa-integrity",
            "args": ["--json"]
        }]"#;
        let hooks: Vec<RegisteredHook> = serde_json::from_str(json).unwrap();
        assert_eq!(hooks.len(), 1);
        assert_eq!(hooks[0].event, "pre-commit");
        assert_eq!(hooks[0].args, vec!["--json"]);
    }

    #[test]
    fn hook_command_line_node_runtime() {
        let hook = RegisteredHook {
            plugin: "test".to_string(),
            key: "test-hook".to_string(),
            event: "pre-commit".to_string(),
            runtime: "node".to_string(),
            entrypoint: "dist/hook.js".to_string(),
            args: vec!["--json".to_string()],
        };
        let cmd = hook_command_line(&hook);
        assert_eq!(cmd, "node \"dist/hook.js\" \"--json\"");
    }

    #[test]
    fn hook_command_line_system_runtime() {
        let hook = RegisteredHook {
            plugin: "test".to_string(),
            key: "test-hook".to_string(),
            event: "pre-commit".to_string(),
            runtime: "system".to_string(),
            entrypoint: "scripts/check.sh".to_string(),
            args: vec![],
        };
        let cmd = hook_command_line(&hook);
        assert_eq!(cmd, "\"scripts/check.sh\"");
    }

    #[test]
    fn generate_dispatcher_includes_marker() {
        let hook = RegisteredHook {
            plugin: "@orqastudio/plugin-integrity".to_string(),
            key: "pre-commit-integrity".to_string(),
            event: "pre-commit".to_string(),
            runtime: "node".to_string(),
            entrypoint: "node_modules/.bin/orqa-integrity".to_string(),
            args: vec!["--json".to_string()],
        };
        let script = generate_dispatcher("pre-commit", &[&hook]);
        assert!(script.contains(GENERATED_MARKER));
        assert!(script.contains("orqa-integrity"));
        assert!(script.contains("legacy"));
    }

    #[test]
    fn generate_dispatcher_multiple_hooks() {
        let hook1 = RegisteredHook {
            plugin: "plugin-a".to_string(),
            key: "check-a".to_string(),
            event: "pre-commit".to_string(),
            runtime: "node".to_string(),
            entrypoint: "a/check.js".to_string(),
            args: vec![],
        };
        let hook2 = RegisteredHook {
            plugin: "plugin-b".to_string(),
            key: "check-b".to_string(),
            event: "pre-commit".to_string(),
            runtime: "system".to_string(),
            entrypoint: "b/check.sh".to_string(),
            args: vec![],
        };
        let script = generate_dispatcher("pre-commit", &[&hook1, &hook2]);
        assert!(script.contains("plugin-a"));
        assert!(script.contains("plugin-b"));
        assert!(script.contains("check-a"));
        assert!(script.contains("check-b"));
    }

    #[test]
    fn git_hook_filename_maps_known_events() {
        assert_eq!(git_hook_filename("pre-commit"), Some("pre-commit"));
        assert_eq!(git_hook_filename("post-commit"), Some("post-commit"));
        assert_eq!(git_hook_filename("pre-push"), Some("pre-push"));
    }

    #[test]
    fn git_hook_filename_returns_none_for_app_events() {
        assert_eq!(git_hook_filename("artifact-change"), None);
        assert_eq!(git_hook_filename("session-start"), None);
    }

    #[test]
    fn read_hook_registry_returns_empty_for_missing_file() {
        let hooks = read_hook_registry(Path::new("/nonexistent"));
        assert!(hooks.is_empty());
    }

    #[test]
    fn generate_dispatchers_with_no_hooks() {
        let temp = std::env::temp_dir().join("orqa_test_hooks_empty");
        let _ = std::fs::create_dir_all(&temp);
        let result = generate_dispatchers(&temp);
        assert!(result.is_ok());
        let result = result.unwrap();
        assert_eq!(result.dispatchers_written, 0);
        let _ = std::fs::remove_dir_all(&temp);
    }

    #[test]
    fn generate_dispatchers_writes_script() {
        let temp = std::env::temp_dir().join("orqa_test_hooks_write");
        let _ = std::fs::remove_dir_all(&temp);
        std::fs::create_dir_all(&temp).unwrap();

        // Write a plugin-hooks.json
        let hooks_json = r#"[{
            "plugin": "test-plugin",
            "key": "test-hook",
            "event": "pre-commit",
            "runtime": "node",
            "entrypoint": "dist/hook.js",
            "args": []
        }]"#;
        std::fs::write(temp.join("plugin-hooks.json"), hooks_json).unwrap();

        let result = generate_dispatchers(&temp).unwrap();
        assert_eq!(result.dispatchers_written, 1);
        assert_eq!(result.events, vec!["pre-commit"]);

        let script = std::fs::read_to_string(temp.join(".githooks/pre-commit")).unwrap();
        assert!(script.contains("AUTO-GENERATED"));
        assert!(script.contains("test-plugin"));

        let _ = std::fs::remove_dir_all(&temp);
    }

    #[test]
    fn generate_dispatchers_preserves_legacy_hook() {
        let temp = std::env::temp_dir().join("orqa_test_hooks_legacy");
        let _ = std::fs::remove_dir_all(&temp);
        std::fs::create_dir_all(temp.join(".githooks")).unwrap();

        // Write an existing non-generated pre-commit hook
        std::fs::write(
            temp.join(".githooks/pre-commit"),
            "#!/bin/bash\necho legacy\n",
        )
        .unwrap();

        // Write a plugin-hooks.json
        let hooks_json = r#"[{
            "plugin": "test-plugin",
            "key": "test-hook",
            "event": "pre-commit",
            "runtime": "node",
            "entrypoint": "dist/hook.js",
            "args": []
        }]"#;
        std::fs::write(temp.join("plugin-hooks.json"), hooks_json).unwrap();

        let result = generate_dispatchers(&temp).unwrap();
        assert_eq!(result.dispatchers_written, 1);

        // Legacy hook should be preserved
        let legacy = std::fs::read_to_string(temp.join(".githooks/pre-commit.legacy")).unwrap();
        assert!(legacy.contains("echo legacy"));

        // New dispatcher should exist
        let dispatcher = std::fs::read_to_string(temp.join(".githooks/pre-commit")).unwrap();
        assert!(dispatcher.contains("AUTO-GENERATED"));
        assert!(dispatcher.contains("pre-commit.legacy"));

        let _ = std::fs::remove_dir_all(&temp);
    }
}
